In [113]:
import numpy as np
from sklearn.model_selection import StratifiedKFold

In [156]:
class Neuron:
    def __init__(self, input_shape):
      self.input_shape = input_shape
      self.bias = 1      
      self.bias_weight = np.random.uniform(low=-1, high=1.0, size=1)
      self.weight_matrix = np.random.uniform(low=-1, high=1.0, size=self.input_shape)

    def sigmoid(self,x):
      return 1/(1+np.exp(-x))
    
    def threshold(self, x):
      if x >= 0:
        return 1
      else:
        return -1
    
    def compute_dot_product(self):
      return np.dot(self.input_layer, self.weight_matrix)
    
    def activate(self, x, activation):
      if activation == 'linear':
        return x
      if activation == 'sigmoid':
        return self.sigmoid(x)
      if activation == 'tanh':
        return np.tanh(x)
      if activation == 'threshold':
        return self.threshold(x)

      
class Layer():
  def __init__(self, input_shape): 
    self.neurons = []
    self.input_shape = input_shape
    for i in range(input_shape[0]):
      self.neurons.append(Neuron(input_shape=input_shape[1]))
    
    
    
class MultiLayerPerceptron: 
  
  def build_layers(self, input_shape):
    for i in range(0, len(input_shape)-1):
      self.layers.append(Layer(input_shape=(input_shape[i+1],input_shape[i])))
  
  '''
      input_shape: Array or tuple with the corresponding
      number of neurons per layer.
      
  '''
  def __init__(self, input_shape):
    self.layers = [] # to_do replace layers by weight matrix
    self.build_layers(input_shape)
    self.weight_matrix = [None] * len(input_shape)
    self.weight_matrix[0] = np.random.uniform(low=-1, high=1.0, size=(input_shape[0]))
    
    # nao bolir
    for i in range(0, len(input_shape)-1):
      self.weight_matrix[i+1] = np.random.uniform(low=-1, high=1.0, size=(input_shape[i+1],input_shape[i])) # one column added to the corresponding bias weight
    for i in range(len(self.weight_matrix)):
      print(self.weight_matrix[i].shape)
    self.input_shape = input_shape

    
  def forward_pass(self, X, y,):
    output_results = None * [len(input_shape)]
    print('Input Layer:', nn.weight_matrix[0])
    result = np.dot(nn.weight_matrix[0], np.transpose(nn.weight_matrix[1])) 
    print(result)
    for i in range(2,len(nn.weight_matrix)):
      result = np.dot(result, np.transpose(nn.weight_matrix[i]))
      print(result)    
    
  def fit(X, y, self, learning_rate, error):
    prev_mse = 999999999
    current_mse  = 0
    epochs = 0 
    for (X,y) in zip(X,y):
      self.forward_pass()


      
nn = MultiLayerPerceptron(input_shape=[4,5,2])

(4,)
(5, 4)
(2, 5)


In [165]:
print(len(nn.layers[1].neurons))
print(nn.layers[1].neurons[0].weight_matrix.shape)

2
(5,)


In [125]:
nn.weight_matrix[0]

array([ 0.04699908,  0.99040976,  0.16943584, -0.6951866 ])

In [179]:
nn.weight_matrix[1][0] = nn.layers[0].neurons[0].weight_matrix
nn.weight_matrix[1][1] = nn.layers[0].neurons[1].weight_matrix
nn.weight_matrix[1][2] = nn.layers[0].neurons[2].weight_matrix
nn.weight_matrix[1][3] = nn.layers[0].neurons[3].weight_matrix
nn.weight_matrix[1][4] = nn.layers[0].neurons[4].weight_matrix

nn.weight_matrix[2][0] = nn.layers[1].neurons[0].weight_matrix
nn.weight_matrix[2][1] = nn.layers[1].neurons[1].weight_matrix


In [178]:
nn.weight_matrix[1]

array([[ 0.0064998 , -0.90824681,  0.4511967 ,  0.38126342],
       [-0.02559393, -0.96612846, -0.97580469, -0.35306964],
       [-0.13126531,  0.40257782, -0.15195659, -0.36147041],
       [-0.76454793, -0.71972794, -0.27620146, -0.39473405],
       [-0.67951896,  0.97103497, -0.65180555, -0.80274133]])

In [180]:
nn.weight_matrix[2]

array([[ 0.18495092, -0.86836416, -0.75961789,  0.72854048,  0.82209979],
       [ 0.21770129,  0.86738986,  0.36344591, -0.22531492, -0.70578798]])

In [130]:
nn.weight_matrix[2]

array([[-0.60601595, -0.1589983 , -0.36605246, -0.26730827, -0.57486168],
       [ 0.35831912,  0.49635072, -0.1531997 , -0.94263657,  0.93524953]])

In [173]:
for neuron in nn.layers[0].neurons:
  print('Bias:' , neuron.bias)
  print('Bias weight:', neuron.bias_weight)
  print('Weight Matrix:', neuron.weight_matrix)

Bias: 1
Bias weight: [0.93687414]
Weight Matrix: [ 0.0064998  -0.90824681  0.4511967   0.38126342]
Bias: 1
Bias weight: [0.86596015]
Weight Matrix: [-0.02559393 -0.96612846 -0.97580469 -0.35306964]
Bias: 1
Bias weight: [0.1438388]
Weight Matrix: [-0.13126531  0.40257782 -0.15195659 -0.36147041]
Bias: 1
Bias weight: [-0.12865326]
Weight Matrix: [-0.76454793 -0.71972794 -0.27620146 -0.39473405]
Bias: 1
Bias weight: [-0.8138621]
Weight Matrix: [-0.67951896  0.97103497 -0.65180555 -0.80274133]


In [199]:
input_pattern = nn.weight_matrix[0]
print('Input Pattern:', input_pattern)
first_out = []
for neuron in nn.layers[0].neurons:
  dot = np.dot(input_pattern, neuron.weight_matrix) # TODO add: neuron.bias * neuron.bias_weight[0] +
  first_out.append(dot)
output_by_layer = [first_out]
for i in range(len(nn.layers)-1):
  layer_out = []
  for neuron in nn.layers[i+1].neurons:
    dot = np.dot(output_by_layer[i], neuron.weight_matrix) # TODO add: neuron.bias * neuron.bias_weight[0] +
    layer_out.append(dot)
  output_by_layer.append(layer_out)
print(output_by_layer[0])
print(output_by_layer[1])


Input Pattern: [ 0.34881264  0.72391224  0.47972441 -0.52115885]
[-0.6374725095774028, -0.9924316610901016, 0.3611302274664668, -0.714485281637435, 0.5715880066328145]
[0.41894091094422103, -1.1107881920645735]


In [183]:
nn.layers[0].neurons[0].bias_weight

array([0.93687414])

In [182]:
# forward pass function:
print('Input Layer:', nn.weight_matrix[0])
result = np.dot(nn.weight_matrix[0], np.transpose(nn.weight_matrix[1])) 
print(result)
for i in range(2,len(nn.weight_matrix)):
  result = np.dot(result, np.transpose(nn.weight_matrix[i]))
  print(result)

Input Layer: [ 0.34881264  0.72391224  0.47972441 -0.52115885]
[-0.63747251 -0.99243166  0.36113023 -0.71448528  0.57158801]
[ 0.41894091 -1.11078819]


In [13]:
nn.weight_matrix[0]

array([[ 0.00111759,  0.67598335, -0.87129364, -0.48858705],
       [-0.61768803,  0.70156015, -0.88117519, -0.3185993 ],
       [-0.53684066, -0.04649365, -0.19035894, -0.03218577],
       [ 0.12676204, -0.18736079,  0.63508442, -0.68610225],
       [-0.83814944,  0.90275327, -0.13131897, -0.01142184]])

In [91]:
def assembly_dataset():
  f = open("iris.data", "r")
  data_x = []
  data_y = []
  for line in f:
    if len(line) != 1:
      data = line.replace('\n', '')
      t = data.split(',')
      data_y.append(t.pop(4))
      data_x.append(np.array(t,dtype=np.float32))
  return data_x, data_y

def normalize_row(row, max_val, min_val):
  for i in range(len(row)):
    row[i] = (2 * ((row[i] - min_val)/(max_val - min_val))) - 1 

def find_max_min(features):
  max_val = features[0][0]
  min_val = features[0][0]
  for i in range(len(features)):
    max_test = features[i][np.argmax(features[i])] 
    if max_test > max_val:
      max_val = max_test
      
    min_test = features[i][np.argmin(features[i])] 
    if min_test < min_val:
      min_val = min_test
  return max_val, min_val
    
def feature_normalization(features):
  max_val, min_val = find_max_min(features)
  for feature in features:
    normalize_row(feature, max_val, min_val)
    


In [99]:
def preprocess_dataset():  
  features, labels = assembly_dataset()
  feature_normalization(features)  

  data_dictionary = {'Iris-virginica' : [], 'Iris-versicolor': [], 'Iris-setosa': []}

  one_hot_label_dictionary = {'Iris-virginica' : [1,0,0], 'Iris-versicolor': [0,1,0], 'Iris-setosa': [0,0,1]}

  for t in zip(features,labels):
    data_dictionary[t[1]].append(t[0])
  return (data_dictionary, one_hot_label_dictionary)
data = preprocess_dataset()
print(data[0])
print(data[1])

{'Iris-virginica': [array([ 0.5897436 , -0.17948717,  0.5128205 , -0.38461536], dtype=float32), array([ 0.46153855, -0.3333333 ,  0.2820512 , -0.53846157], dtype=float32), array([ 0.7948718 , -0.25641024,  0.48717952, -0.48717952], dtype=float32), array([ 0.5897436 , -0.28205127,  0.4102564 , -0.5641026 ], dtype=float32), array([ 0.64102566, -0.25641024,  0.46153855, -0.46153843], dtype=float32), array([ 0.92307687, -0.25641024,  0.6666666 , -0.48717952], dtype=float32), array([ 0.23076928, -0.38461536,  0.12820518, -0.5897436 ], dtype=float32), array([ 0.84615386, -0.28205127,  0.5897436 , -0.5641026 ], dtype=float32), array([ 0.6923076 , -0.38461536,  0.46153855, -0.5641026 ], dtype=float32), array([ 0.8205128 , -0.1025641 ,  0.53846145, -0.38461536], dtype=float32), array([ 0.64102566, -0.2051282 ,  0.2820512 , -0.51282054], dtype=float32), array([ 0.6153846 , -0.3333333 ,  0.33333337, -0.53846157], dtype=float32), array([ 0.7179488 , -0.25641024,  0.38461542, -0.48717952], dtype=fl

In [112]:
data[0]['Iris-setosa']

[array([ 0.2820512 , -0.12820512, -0.6666667 , -0.974359  ], dtype=float32),
 array([ 0.23076928, -0.25641024, -0.6666667 , -0.974359  ], dtype=float32),
 array([ 0.17948711, -0.2051282 , -0.6923077 , -0.974359  ], dtype=float32),
 array([ 0.15384614, -0.23076928, -0.64102566, -0.974359  ], dtype=float32),
 array([ 0.25641024, -0.1025641 , -0.6666667 , -0.974359  ], dtype=float32),
 array([ 0.35897434, -0.02564102, -0.5897436 , -0.9230769 ], dtype=float32),
 array([ 0.15384614, -0.15384614, -0.6666667 , -0.94871795], dtype=float32),
 array([ 0.25641024, -0.15384614, -0.64102566, -0.974359  ], dtype=float32),
 array([ 0.1025641 , -0.28205127, -0.6666667 , -0.974359  ], dtype=float32),
 array([ 0.23076928, -0.23076928, -0.64102566, -1.        ], dtype=float32),
 array([ 0.35897434, -0.07692307, -0.64102566, -0.974359  ], dtype=float32),
 array([ 0.2051282 , -0.15384614, -0.61538464, -0.974359  ], dtype=float32),
 array([ 0.2051282 , -0.25641024, -0.6666667 , -1.        ], dtype=float32),

In [119]:
 # stratified random sampling
labels = list(data[1].keys())
X = []
y = []
for i in range(len(labels)):
  for x_sample in data[0][labels[i]]:
    X.append(x_sample)
    y.append(i)
    
skf = StratifiedKFold(n_splits=10) # shuffle and configure seed.
skf.get_n_splits(X, y)
for i, (train_index, test_index) in enumerate(skf.split(X, y)):
  print(f"Fold {i}:")
  print(f"  Train: index={train_index}")
  print(f"  Test:  index={test_index}")

Fold 0:
  Train: index=[  5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20  21  22
  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40
  41  42  43  44  45  46  47  48  49  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122
 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140
 141 142 143 144 145 146 147 148 149]
  Test:  index=[  0   1   2   3   4  50  51  52  53  54 100 101 102 103 104]
Fold 1:
  Train: index=[  0   1   2   3   4  10  11  12  13  14  15  16  17  18  19  20  21  22
  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40
  41  42  43  44  45  46  47  48  49  50  51  52  53  54  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90

In [116]:
for i in range(len(test_index)):
  print(y[test_index[i]])

0
0
0
0
0
1
1
1
1
1
2
2
2
2
2


In [77]:
feature_normalization(features)
#print(features)

524


IndexError: list index out of range

ValueError: too many values to unpack (expected 2)

TypeError: feature_normalization() missing 1 required positional argument: 'features'

In [53]:
data_dictionary

{'Iris-virginica': [['6.3', '3.3', '6.0', '2.5'],
  ['5.8', '2.7', '5.1', '1.9'],
  ['7.1', '3.0', '5.9', '2.1'],
  ['6.3', '2.9', '5.6', '1.8'],
  ['6.5', '3.0', '5.8', '2.2'],
  ['7.6', '3.0', '6.6', '2.1'],
  ['4.9', '2.5', '4.5', '1.7'],
  ['7.3', '2.9', '6.3', '1.8'],
  ['6.7', '2.5', '5.8', '1.8'],
  ['7.2', '3.6', '6.1', '2.5'],
  ['6.5', '3.2', '5.1', '2.0'],
  ['6.4', '2.7', '5.3', '1.9'],
  ['6.8', '3.0', '5.5', '2.1'],
  ['5.7', '2.5', '5.0', '2.0'],
  ['5.8', '2.8', '5.1', '2.4'],
  ['6.4', '3.2', '5.3', '2.3'],
  ['6.5', '3.0', '5.5', '1.8'],
  ['7.7', '3.8', '6.7', '2.2'],
  ['7.7', '2.6', '6.9', '2.3'],
  ['6.0', '2.2', '5.0', '1.5'],
  ['6.9', '3.2', '5.7', '2.3'],
  ['5.6', '2.8', '4.9', '2.0'],
  ['7.7', '2.8', '6.7', '2.0'],
  ['6.3', '2.7', '4.9', '1.8'],
  ['6.7', '3.3', '5.7', '2.1'],
  ['7.2', '3.2', '6.0', '1.8'],
  ['6.2', '2.8', '4.8', '1.8'],
  ['6.1', '3.0', '4.9', '1.8'],
  ['6.4', '2.8', '5.6', '2.1'],
  ['7.2', '3.0', '5.8', '1.6'],
  ['7.4', '2.8', '6.1'